return {
  --  {
  --    "nvim-tree/nvim-tree.lua",
  --    config = function()
  --      require("nvim-tree").setup({
  --        view = {
  --          relativenumber = true,
  --          width = 30,
  --        },
  --        sort = {
  --          sorter = "case_sensitive",
  --        },
  --        renderer = {
  --          group_empty = true,
  --        },
  --        filters = {
  --          dotfiles = false,
  --        },
  --      })
  --    end,
  --  }
}
